baseurl      = "localhost"
title        = "My Blog"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[permalinks]
  posts = "/posts/:year/:month/:title/"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"  

[params]

  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Hi! 😄 SRE/DevOps engineer @ SIU"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = true
  enableThemeToggle = true
  #backgroundImage = "https://gifdb.com/images/high/swinging-cartoon-cat-3yxcbdsbj0eecq25.gif"

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

    [params.favicon.color]
    mask = "#1b1c1d"
    msapplication = "#1b1c1d"
    theme = "#1b1c1d"

    [params.footer]
    trademark = 2024
    copyright = true
    author = true

    topText = []
    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
      "Template made by <a href=\"https://github.com/rhazdon\">Djordje Atlialp</a> and customized by <a href=\"https://github.com/nicoacu\">me</a>."
    ]  

[languages]
  [languages.en]
    title = "Nicolas Ignacio Acuna"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

  [languages.en.params]
    subtitle  = "A simple theme for Hugo"
    readOtherPosts = "Read other posts"  
    keywords = ""

    [languages.en.params.logo]
    logoMark     = ">"
    logoText     = "$cd /index/"
    logoHomeLink = "/"
    # Set true to remove the logo cursor entirely.
    logoCursorDisabled = false
    # Set to a valid CSS color to change the cursor in the logo.
    logoCursorColor    = "#ffa500"
    # Set to a valid CSS time value to change the animation duration, "0s" to disable.
    # logoCursorAnimate  = "2s"
    # Append the current url pathname to logoText 
    logoCursorPathname = true

  # And you can even create generic menu

  [[params.social]]
    name = "email"
    url  = "mailto:nobody@example.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/nicoacu"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/nicolasignacioacu/"

  [menu]
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
    weight     = 10

  [[menu.main]]
    identifier = "bibliops"
    name       = "Bibliops"
    url        = "/wiki"

[[menu.main]]
  identifier = "cv"
  name = "CV"
  url = 'https://nicoacu.github.io/CV/'
  [menu.main.params]
    rel="external"
    target="_blank"



