baseurl      = "localhost"
title        = "My Blog"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[permalinks]
  posts = "/posts/:year/:month/:title/"

[taxonomies]
    category = "categories"
    tag      = "tags"
    series   = "series"  

[params]

  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = false
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = true
  enableThemeToggle = true
  #backgroundImage = "https://gifdb.com/images/high/swinging-cartoon-cat-3yxcbdsbj0eecq25.gif"

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

    [params.favicon.color]
    mask = "#1b1c1d"
    msapplication = "#1b1c1d"
    theme = "#1b1c1d"

    [params.footer]
    trademark = 2024
    copyright = true
    author = true

    topText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>"
    ]
    bottomText = [
      "Template made by <a href=\"https://github.com/rhazdon\">Djordje Atlialp</a> and customized by <a href=\"https://github.com/nicoacu\">me</a>."
    ]  

[languages]
  [languages.en]
    title = "Nico Acuna"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

  [languages.en.params]
    homeSubtitle = "Here's where I document everything that I think will need in the future so...You're welcome future me <3"
    subtitle  = "en"
    readOtherPosts = "Read other posts"  
    keywords = "nicoacu, nicolas ignacio acu"

    [languages.en.params.logo]
    logoMark     = ">"
    logoText     = "$cd /index/"
    logoHomeLink = "/"
    logoCursorDisabled = false # Set true to remove the logo cursor entirely.
    logoCursorColor    = "#ffa500" # Set to a valid CSS color to change the cursor in the logo.
    #logoCursorAnimate  = "2s"    # Set to a valid CSS time value to change the animation duration, "0s" to disable.
    logoCursorPathname = true    # Append the current url pathname to logoText

    [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
    weight     = 10

    [[menu.main]]
    identifier = "bibliops"
    name       = "Bibliops"
    url        = "/wiki"


  [languages.es]
    title = "Nico Acuña"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    
  [languages.es.params]
    homeSubtitle = "Acá es donde documento todo lo que creo que me va a servir en el futuro asi que...de nada futuro yo <3"
    subtitle  = "es"
    readOtherPosts = "Read other posts"  
    keywords = "nicoacu, nicolas ignacio acu"

    [languages.es.params.logo]
    logoMark     = ">"
    logoText     = "$cd /index/"
    logoHomeLink = "/"
    logoCursorDisabled = false # Set true to remove the logo cursor entirely.
    logoCursorColor    = "#ffa500" # Set to a valid CSS color to change the cursor in the logo.
    #logoCursorAnimate  = "2s"    # Set to a valid CSS time value to change the animation duration, "0s" to disable.
    logoCursorPathname = true    # Append the current url pathname to logoText 

    #MENUS ESPANOL
    [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
    weight     = 10

    [[menu.main]]
    identifier = "bibliops"
    name       = "Bibliops"
    url        = "/wiki"

  # And you can even create generic menu

  [[params.social]]
    name = "github"
    url  = "https://github.com/nicoacu"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/nicolasignacioacu/"

  [menu]

[[menu.main]]
  identifier = "cv"
  name = "CV"
  url = 'https://nicoacu.github.io/CV/'
  rel="external"
  target="_blank"

  [menu.main.params]
    



